export default function SourceIssues({ farnleyImported, morleyApproxTurnout, sourceDecisionsResolved }: { farnleyImported: boolean; morleyApproxTurnout: boolean; sourceDecisionsResolved: boolean }) {
  return <section className="card source-issues"><h2>Leeds result source decisions</h2>
    <p>These limits affect source certainty and historical completeness. The published package and exports label the affected records; missing votes are never shown as zero.</p>
    <ul>
      <li><strong>Farnley &amp; Wortley, 10 October 2024:</strong> the <a href="https://datamillnorth.org/download/20jwj/7f3/Farnley%20%26%20Wortley%20ward%20by-election%20-%2010%20October%202024.pdf" target="_blank" rel="noreferrer">council-hosted declaration</a> has zeros for all candidates and names no winner. {farnleyImported ? <>The published candidate votes and 20.15% turnout come from <a href="https://westleedsdispatch.com/farnley-wortley-by-election-result-green-partys-david-blackburn-retakes-seat/" target="_blank" rel="noreferrer">West Leeds Dispatch</a>, a secondary local report. They are labelled as such in the result and exports.</> : "This package excludes its candidate votes and does not treat the blank result as zero."} A corrected council declaration is still sought.</li>
      <li><strong>Morley South, 12 June 2025:</strong> the council declaration supplies the complete candidate tally and 13 rejected ballots. {morleyApproxTurnout ? "The 31.7% turnout is an approximate secondary-source figure; that account’s ballot count differs by one from the declaration. The result and exports label this distinction." : "This package has no checked turnout percentage."}</li>
      {sourceDecisionsResolved ? <li><strong>Historical source choices closed for this release:</strong> Kirkstall 2021 and Roundhay 2024 use the <a href="https://datamillnorth.org/dataset/local-election-results-20jwj" target="_blank" rel="noreferrer">council archive</a> figures; Calverley &amp; Farsley and Headingley &amp; Hyde Park 2023 use the <a href="https://www.electionscentre.co.uk/wp-content/uploads/2024/01/LEH-2023-Complete.pdf" target="_blank" rel="noreferrer">Local Elections Handbook</a> because the council spreadsheet contains zero fields. All four contests carry a source note. The original disagreement remains documented; it is no longer an unresolved publication decision.</li> : <li><strong>Fifteen candidate-vote differences:</strong> four ward/year contests in 2021, 2023 and 2024 differ between council archive files and the Local Elections Handbook. This older release used Handbook figures and marked each affected contest.</li>}
      <li><strong>Election-event coverage:</strong> {sourceDecisionsResolved ? <>The <a href="https://datamillnorth.org/dataset/local-election-results-20jwj" target="_blank" rel="noreferrer">published council archive</a> was checked through 26 September 2026: its two stand-alone by-election files, Farnley &amp; Wortley 2024 and Morley South 2025, are represented, as are extra seats filled at ordinary polls. This closes the defined archive reconciliation, though it is not a certified councillor-by-councillor history.</> : "The imported event register has not yet been reconciled against the full published council archive."} “Latest recorded” means the newest imported poll for a ward, not a confirmed current councillor.</li>
    </ul>
    <h3>Councillor changes and vacancies</h3>
    <p>A councillor changing party alters council composition without another poll. The 2024–26 changes list records Trish Smith moving Conservative → Independent → Reform UK, and Abigail Marshall Katung and Zara Hussain leaving Labour to sit as independents. Mark Sewards and Wyn Kidger resigned; their vacancies led to the Farnley &amp; Wortley and Morley South by-elections above. The early-2026 death or resignations listed there were handled as vacancies in the May 2026 election, which contested additional seats in three wards. These event descriptions are <a href="https://en.wikipedia.org/wiki/2024_Leeds_City_Council_election#Defections_and_resignations" target="_blank" rel="noreferrer">secondary-source timeline notes</a>, not a certified full councillor register.</p>
    <p>Since May 2026, Jessica Lennox and Cristiana Mirosanu are reported as sitting independently after leaving Labour and Green respectively; Peter Carlill&apos;s resignation created the Calverley &amp; Farsley vacancy, with a by-election announced for 22 October 2026. <a href="https://en.wikipedia.org/wiki/2026_Leeds_City_Council_election#Changes_between_2026_and_2027" target="_blank" rel="noreferrer">Event account</a> · <a href="https://www.leeds.gov.uk/elections/leeds-city-council-elections" target="_blank" rel="noreferrer">Council poll notice</a>. The Composition view uses the council&apos;s dated <a href="https://www.leeds.gov.uk/councillors-and-democracy/councillors-and-committees" target="_blank" rel="noreferrer">99-seat count</a>; it is separate from poll winners and can change between releases.</p>
    <p className="footnote">Full record: <a href={sourceDecisionsResolved ? "https://github.com/amounderness/hq-dashboard-frontend/blob/feature/switchboard-leeds-explorer/docs/leeds-source-decisions-v0.6.0-2026-09-26.md" : "https://github.com/amounderness/hq-dashboard-frontend/blob/feature/switchboard-leeds-explorer/docs/leeds-source-issues-2026-09-26.md"} target="_blank" rel="noreferrer">Leeds source decisions and audit</a>.</p>
  </section>;
}
