export default function SourceIssues({ farnleyImported, morleyApproxTurnout }: { farnleyImported: boolean; morleyApproxTurnout: boolean }) {
  return <section className="card source-issues"><h2>Leeds result source decisions</h2>
    <p>These limits affect source certainty and historical completeness. The published package and exports label the affected records; missing votes are never shown as zero.</p>
    <ul>
      <li><strong>Farnley &amp; Wortley, 10 October 2024:</strong> the <a href="https://datamillnorth.org/download/20jwj/7f3/Farnley%20%26%20Wortley%20ward%20by-election%20-%2010%20October%202024.pdf" target="_blank" rel="noreferrer">council-hosted declaration</a> has zeros for all candidates and names no winner. {farnleyImported ? <>The published candidate votes and 20.15% turnout come from <a href="https://westleedsdispatch.com/farnley-wortley-by-election-result-green-partys-david-blackburn-retakes-seat/" target="_blank" rel="noreferrer">West Leeds Dispatch</a>, a secondary local report. They are labelled as such in the result and exports.</> : "This package excludes its candidate votes and does not treat the blank result as zero."} A corrected council declaration is still sought.</li>
      <li><strong>Morley South, 12 June 2025:</strong> the council declaration supplies the complete candidate tally and 13 rejected ballots. {morleyApproxTurnout ? "The 31.7% turnout is an approximate secondary-source figure; that account’s ballot count differs by one from the declaration. The result and exports label this distinction." : "This package has no checked turnout percentage."}</li>
      <li><strong>Fifteen candidate-vote differences:</strong> four ward/year contests in 2021, 2023 and 2024 differ between council archive files and the Local Elections Handbook. The release uses Handbook figures, corroborated by its published PDFs, and marks each affected contest. A council correction or explanation is still sought.</li>
      <li><strong>By-election coverage:</strong> the imported event register has not been certified exhaustive. “Latest recorded” means the newest result in this package for a ward, not a confirmed current councillor or complete election history.</li>
    </ul>
    <h3>Councillor changes and vacancies</h3>
    <p>A councillor changing party alters council composition without another poll. The 2024–26 changes list records Trish Smith moving Conservative → Independent → Reform UK, and Abigail Marshall Katung and Zara Hussain leaving Labour to sit as independents. Mark Sewards and Wyn Kidger resigned; their vacancies led to the Farnley &amp; Wortley and Morley South by-elections above. The early-2026 death or resignations listed there were handled as vacancies in the May 2026 election, which contested additional seats in three wards. These event descriptions are <a href="https://en.wikipedia.org/wiki/2024_Leeds_City_Council_election#Defections_and_resignations" target="_blank" rel="noreferrer">secondary-source timeline notes</a>, not a certified full councillor register.</p>
    <p>Since May 2026, Jessica Lennox and Cristiana Mirosanu are reported as sitting independently after leaving Labour and Green respectively; Peter Carlill&apos;s resignation created the Calverley &amp; Farsley vacancy, with a by-election announced for 22 October 2026. <a href="https://en.wikipedia.org/wiki/2026_Leeds_City_Council_election#Changes_between_2026_and_2027" target="_blank" rel="noreferrer">Event account</a> · <a href="https://www.leeds.gov.uk/elections/leeds-city-council-elections" target="_blank" rel="noreferrer">Council poll notice</a>. The Composition view uses the council&apos;s dated <a href="https://www.leeds.gov.uk/councillors-and-democracy/councillors-and-committees" target="_blank" rel="noreferrer">99-seat count</a>; it is separate from poll winners and can change between releases.</p>
    <p className="footnote">Full record: <a href="https://github.com/amounderness/hq-dashboard-frontend/blob/feature/switchboard-leeds-explorer/docs/leeds-source-issues-2026-09-26.md" target="_blank" rel="noreferrer">Leeds source-issue register</a>.</p>
  </section>;
}
